### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [renatapro/zadanie12.2#1]
- [ ] nie potrzebujesz dolaczac `jquery-ui`, wystarczy samo `jquery`
- [ ] sprobuj opublikowac strone na github pages zeby zobaczyc jak dziala :)

**Comment by renatapro** [comment]
-jak naciskam na buttony to zmienia mi się kolor ramki, czy to ma tak zostać, czy mam to zmienić żeby cały czas była biała ramka, w sumie to nawet nie wiem czemu się zmienia bo ja nic nie ustawiałam,

- a jeśli chodzi o github pages to na razie coś mi nie wychodzi, ale doczytam co robię nie tak:)

**Comment by zdolny** [comment]
ok, github pages zostawiam Ci do potestowania w wolnym czasie, a jesli chodzi o ramke, to sa to domyslne style przegladarki, musialabys dodac buttonowi `outline: none;`

Na ten moment dla mnie wszystko gra - super, ze dorzucilas ten patent z prefixem

zamykam issue :)
